#!/usr/bin/python3

import random
from random import randint
import tkinter
from tkinter.messagebox import *


window = tkinter.Tk()
window.title("GENERATOR DANYCH")
window.geometry("400x200")
#POLE TEKSTOWE
poleTekstowe = tkinter.Text(master=window, width=30, height=10)
poleTekstowe.pack(side=tkinter.RIGHT)


def nip():
    #poleTekstowe.configure(state=tkinter.NORMAL)
    poleTekstowe.delete("0.0",tkinter.END)
    a = randint(0, 9)
    b = randint(0, 9)
    c = randint(0, 9)
    d = randint(0, 9)
    e = randint(1, 3)
    f = randint(0, 9)
    g = randint(0, 9)
    h = randint(0, 9)
    i = randint(0, 9)
    j = (6 * a + 5 * b + 7 * c + 2 * d + 3 * e + 4 * f + 5 * g + 6 * h + 7 * i) % 11
    while j == 10:
        a = randint(0, 9)
        b = randint(0, 9)
        c = randint(0, 9)
        d = randint(0, 9)
        e = randint(1, 3)
        f = randint(0, 9)
        g = randint(0, 9)
        h = randint(0, 9)
        i = randint(0, 9)
        j = (6 * a + 5 * b + 7 * c + 2 * d + 3 * e + 4 * f + 5 * g + 6 * h + 7 * i) % 11
    print (j)
    j = str(j)
    nip_caly = str(a) + str(b) + str(c) + str(d) + str(e) + str(f) + str(g) + str(h) + str(i) + str(j)
    print ("NIP:" + nip_caly)
    poleTekstowe.insert(tkinter.END, "NIP:" + nip_caly + "\n")
    poleTekstowe.clipboard_append(nip)
    poleTekstowe.see(tkinter.END)


def pesel():
    poleTekstowe.delete("0.0", tkinter.END)
    #PRZYKŁADOWE LISTY IMION
    imiona_mez = ["Tomasz", "Edmund", "Pafnucy"]
    imiona_kobiet = ["Zofia", "Barbara", "Marzena"]
    imiona = [imiona_kobiet, imiona_mez]
    plec = random.choice(imiona)
    imie = random.choice(plec)
    print (imie)

    # GENERATOR NAZWISK NA BAZIE PLCI
    #PRZYKŁADOWE LISTY NAZWISK
    nazwiska_mez = ["Złotopolski", "Pieniaski", "Waryński"]
    nazwiska_kob = ["Konwieczówna", "Namakalska", "Domalska"]
    nazwiska = [nazwiska_mez, nazwiska_mez]
    if plec == imiona_kobiet:
        nazwisko = random.choice(nazwiska_kob)
    else:
        nazwisko = random.choice(nazwiska_mez)
    print (nazwisko)
    
    # GENERATOR PESEL
    a = randint(0, 9)
    b = randint(0, 9)
    c = randint(0, 9)
    d = randint(0, 9)
    e = randint(1, 3)
    f = randint(0, 9)
    g = randint(0, 9)
    h = randint(0, 9)
    i = randint(0, 9)
    if plec == imiona_kobiet:
        parzyste = [0, 2, 4, 6, 8]
        j = random.choice(parzyste)
    else:
        nieparzyste = [1, 3, 5, 7, 9]
        j = random.choice(nieparzyste)
    if (a == 0):
        b = randint(1, 9)
        c = 2
    kont = 9 * a + 7 * b + 3 * c + 1 * d + 9 * e + 7 * f + 3 * g + 1 * h + 9 * i + 7 * j
    kont = str(kont)
    pesel_caly = str(a) + str(b) + str(c) + str(d) + str(e) + str(f) + str(g) + str(h) + str(i) + str(j) + kont[2]
    print ("PESEL:" + pesel_caly)
    poleTekstowe.insert(tkinter.END, "PESEL:" + pesel_caly + "\n")
    poleTekstowe.insert(tkinter.END, "IMIE:" + imie + "\n")
    poleTekstowe.insert(tkinter.END, "NAZWISKO:" + nazwisko + "\n")
    poleTekstowe.clipboard_append(pesel)
    poleTekstowe.see(tkinter.END)


def regon():
    poleTekstowe.delete("0.0", tkinter.END)
    a = randint(0, 9)
    b = randint(0, 9)
    c = randint(0, 9)
    d = randint(0, 9)
    e = randint(1, 3)
    f = randint(0, 9)
    g = randint(0, 9)
    h = randint(0, 9)
    i = randint(0, 9)
    kontR = (8 * a + 9 * b + 2 * c + 3 * d + 4 * e + 5 * f + 6 * g + 7 * h + 9) % 11
    if kontR == 10:
        kontR = 0
    kontR = str(kontR)
    regon_caly = str(a) + str(b) + str(c) + str(d) + str(e) + str(f) + str(g) + str(h) + str(i) + kontR
    regon = regon_caly
    print("REGON:" + regon)
    poleTekstowe.insert(tkinter.END, "REGON:" + regon + "\n")
    poleTekstowe.clipboard_append(pesel)
    poleTekstowe.see(tkinter.END)

etykietaNIP = tkinter.Label(window, text = "NIP").pack()
przyciskNIP = tkinter.Button(window, text = "GENERUJ", command = lambda: nip() ).pack()
etykietaPES = tkinter.Label(window, text = "PESEL").pack()
przyciskPES = tkinter.Button(window, text = "GENERUJ", command = lambda: pesel() ).pack()
etykietaREG = tkinter.Label(window, text = "REGON").pack()
przyciskREG = tkinter.Button(window, text = "GENERUJ", command = lambda: regon() ).pack()


#etykietaIB = tkinter.Label(window, text = "IBAN").pack()
#przyciskIB = tkinter.Button(window, text = "GENERUJ").pack()
window.mainloop()
